### ISSUE TITLE
Problem in training the discriminator

### ISSUE THREAD

**Issue by shruti51** [fwt-team/VaGAN-pytorch#1]
Hello
I tried to train the VaGAN as per the given instructions. Pretraining was successfully done. However, the code got stuck at the discriminator training where discriminator loss is back propagated. I have received the following error message in particular:

 0% 0/500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 317, in <module>
    main()
  File "train.py", line 257, in main
    d_loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 1, 4, 4]] is at version 3752; expected version 3751 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
  0% 0/500 [00:00<?, ?it/s]
![err](https://user-images.githubusercontent.com/12147129/103554060-59b50180-4ed4-11eb-814c-08dd4a3c062b.jpg)

**Comment by shruti51** [comment]
issue solved when I downgraded pytorch to the version mentioned in the requirements. Also installed pillow==6.1.
